### ISSUE TITLE
can't read binary file with Storage function

### ISSUE THREAD

**Issue by lpuglia** [torch/torch7#1071]
When I try to read a binary file using Storage instructions in Torch I do:

torch.DoubleStorage("nnz_te.bin")

But at the moment on my machine I am getting:

[torch.DoubleStorage of size 0]

I just installed torch from 0 on a recently formatted machine. This happens for all the binary files I have, I tried to transfer those files to another machine and when i do the same instruction it reads 10289120 elements:

[torch.DoubleStorage of size 10289120]

How is this possible?

**Comment by lpuglia** [comment]
i just installed an older version of torch (commit 71219a0043ff8d902888f089d57123cf1f1e9d0a) and it works, something is really buggy since the new one i was using (commit 9c2ef7f185c682ea333e06654cb6e5b67dfe7cd2) is not able to load those files.

**Comment by soumith** [comment]
fixed via https://github.com/torch/torch7/commit/89ede3ba90c906a8ec6b9a0f4bef188ba5bb2fd8

**Comment by pierrelzw** [comment]
Hi,

I'm new to torch and git. I installed [torch7](http://torch.ch/docs/getting-started.html#_) on Ubuntu14.04. And I come across the same problem as [#1071](https://github.com/torch/torch7/issues/1071).
Since i don't know how to install older version of torch. I followed changes in [89ede3b](https://github.com/torch/torch7/commit/89ede3ba90c906a8ec6b9a0f4bef188ba5bb2fd8), but i always failed to load .bin file([myPerm.bin.zip](https://github.com/torch/torch7/files/1550779/myPerm.bin.zip)) using torch.FloatStorage(), as shown below. 
`th> torch.FloatStorage("myPerm.bin")

[torch.FloatStorage of size 0]
`
