### ISSUE TITLE
torch Tensor breaks canonical Lua object definition

### ISSUE THREAD

**Issue by ubasu** [torch/torch7#170]
The canonical way to create an object in Lua, as given in the PIL books, is as follows:

```lua
Obj={v=0,t=torch.Tensor(1):zero()}
function Obj:new(t)
   t = t or {}
   self.__index = self
   return setmetatable(t,self)
end
```

However, the tensor component of the object does not behave as expected. If we do

```lua
function Obj:update(n)
   self.v=n
   self.t[1]=n
end

function Obj:print()
   print(self.v,self.t[1])
end

a=Obj:new()
b=Obj:new()

a:update(2)
b:update(3)

a:print()
b:print()
```

then we get 

```lua
2	3	
3	3	
```

We get the expected answer only if we define the object as
```lua
Obj={}
function Obj:new(t)
   t = t or {v=0,t=torch.Tensor(1):zero()}
   self.__index = self
   return setmetatable(t,self)
end
```

Not sure if this is a known issue and if it can be fixed.

**Comment by GeorgOstrovski** [comment]
This has little to do with torch.Tensor. If you replace the very first line of your above code by
``` 
Obj={v=0,t={0}}
```
you will observe exactly the same behaviour. 
The reason is that in Lua an assignment of the form  x = y  is shallow, i.e. copies only a *reference* to the underlying object, whenever y is a table or userdata object (and a torch Tensor is of type userdata). That is, the first version of your above code will initialize every object created by Obj:new with a reference to *the same* tensor t.

**Comment by ubasu** [comment]
OK, thanks for clarifying. ;-)
