### ISSUE TITLE
Wrong transposition in torch.qr

### ISSUE THREAD

**Issue by GeorgOstrovski** [torch/torch7#237]
I believe the current implementation of torch.qr returns a tensor of wrong stride:
```lua
q=torch.Tensor(10,10):zero()
r=torch.Tensor(10,10):zero()
m=torch.Tensor(10,10):uniform()

print(q:stride()) -- 10, 1
torch.qr(q,r,m)
print(q:stride()) -- 1, 10
```

Related, the in-place version doesn't handle a provided return tensor correctly, if it is non-contiguous:
```lua
q=torch.Tensor(10,10):zero():t()
r=torch.Tensor(10,10):zero()
m=torch.Tensor(10,10):uniform()

torch.qr(q,r,m)
err = q*r - m
print(err:abs():max()) -- is not 0 as it should be
```

The above two taken together mean that when one repeatedly uses QR in a loop on the same output tensors, the results are rather surprising. 

I believe the wrong behaviour already happens in torch.geqrf (which has the same issue) - the function lapackClone used there creates a tensor with different strides, which the code below probably doesn't account for when returning the result.

**Comment by d11** [comment]
I have verified that the second point, which to me is the main bug here, is fixed by Koray's 'avoid unnecessary tranpose' change. (It was not specific to torch.qr). The first point, about whether or not qr should return a non-contiguous tensor in the first place, is well-taken. However, other torch LAPACK functions - for example, torch.svd() - also return non-contiguous tensors, since this may be the most efficient thing to do. I will leave it as is unless others object, but we might want to clarify the documentation around the LAPACK functions to make this aspect more explicit...
