### ISSUE TITLE
Suggestion: HalfTensor

### ISSUE THREAD

**Issue by Kaixhin** [torch/torch7#294]
In the same vein as the upcoming update to [CUDA 7.5](http://devblogs.nvidia.com/parallelforall/new-features-cuda-7-5/), a 16-bit floating point type should provide a significant performance benefit, and would also work well with a future "CudaHalfTensor" in `cutorch`.

**Comment by hughperkins** [comment]
Does seem like a good idea.   A fair amount of work, but arguably worth it.

**Comment by dominikgrewe** [comment]
There's no native type in C for that though, is there?

**Comment by hughperkins** [comment]
You mean, should put this suggestoin in `cutorch` directly rather than in `torch7` repo?

**Comment by dominikgrewe** [comment]
It probably makes more sense for cutorch, but it would be quite some effort to implement. We don't even have CudaByteTensor, CudaIntTensor etc :)

**Comment by Kaixhin** [comment]
I just mentioned this in the open CUDA 7 upgrade issue for `cutorch`, so this is at least referenced there.

I see that without a native C type this would be a fair amount of effort. However, given the resurgence of research supporting the ability of neural networks to work effectively with half-precision floating-points, a potential 2x speedup for most applications is worth consideration.

**Comment by soumith** [comment]
I think we'll implement a cutorch tensor type. Not sure if we want to do it for torch (cpu). Will discuss more in cutorch.

**Comment by jonathantompson** [comment]
Were there any further thoughts on this?  Float16 would be extremely useful for my current application.

**Comment by apaszke** [comment]
HalfTensors are already there, but they don't support math right now. AFAIK @wickedfoo is working on it (see e.g. https://github.com/torch/cutorch/pull/431)

**Comment by soumith** [comment]
It's implemented in the current master as CudaHalfTensor. A lot of the pointwise functions are in there as well. Most of the math functions (including blas) were pushed in last week in https://github.com/torch/cutorch/pull/431

They are under review, i have to cut a release for that PR because it introduces small breaking changes, like the gt() method returining a CudaByteTensor now instead of a CudaTensor.

cudnn support for fp16 should be done next week as well, considering @szagoruyko did most of the groundwork and was waiting on simple math support

**Comment by jonathantompson** [comment]
OK, cool.  Thanks for the update.  But there's no C implementation (because C does not have a native fp16 type)?

**Comment by apaszke** [comment]
There's no CPU counterpart at the moment, for the exact reason you mentioned.

**Comment by wickedfoo** [comment]
CPU conversion functions for float16 <-> float32 are in cutorch code (the CPU equivalent of `__float2half` and `__half2float`). One could also write a wrapper that upconverts arguments from float16 -> float32, operates and down-converts again.

However, there's no reason to use float16 on CPU I think, since it will be 1-2 orders of magnitude slower.

**Comment by hughperkins** [comment]
Presumably, the advantage would be that memory bandwidth would be lower?  On-chip, the float16s could be unpacked into fp32s, as you say.  I guess there should be a bunch of memory-bound algorithms that might thus see acceleration?  But maybe they are all done via BLAS currently, and those are all 32/64-bit?

**Comment by jorditg** [comment]
Right now there is a compatibility problem between conversion of CudaHalfTensor because we don't have its CPU counterpart HalfTensor implemented. We now that right now, at least for the x86 architecture, there is not CPU FP16 hardware arithmetic available, so a software implementation would be inneficient. 

In any case, I think that creating a new type: HalfTensor that internally work as a FP32 type would be a way to avoid the actual incompatibility. Afterwards, in those architectures like ARM that have CPU FP16 instructions the type could be implemented to make use of the hardware advantadge and in the others the type would continue making the calculations as FP32.

**Comment by soumith** [comment]
now torch has a torch.HalfTensor to solve this. Thanks all.

**Comment by chaopengshen** [comment]
Why am I see an error why I tried 
local yTensor=torch.HalfTensor(nt,ngrid):zero_()

error says 
attempt to call method 'zero_' (a nil value)

either zero or zero_ is the same

**Comment by chaopengshen** [comment]
Why am I see an error why I tried
local yTensor=torch.HalfTensor(nt,ngrid):zero_()

error says
attempt to call method 'zero_' (a nil value)

either zero or zero_ is the same

**Comment by fmassa** [comment]
@chaopengshen the only operation implemented for `HalfTensor` in the CPU is the `copy` operation, that's why you are seeing this problem. I think there are no plans to add further support for other operations in half tensors in the CPU.

**Comment by chaopengshen** [comment]
Thanks fmassa. Sorry for the question. could you hint, if I just want to testrun our rnn code under half precision mode, what would be an avenue to take? Is that even possible? So, we have this little piece of code which is now using DoublePrecision. How can I proceed to convert it into using HalfPrecision (heard it will be much faster?--at least I did not notice much difference when I changed DoubleTensor to FloatTensor). Thanks.

=====

	xTrain=torch.DoubleTensor(rho,nbatch,nx):zero()
	yTrain=torch.DoubleTensor(rho,nbatch,ny):zero()
	if gpu>0 then
		xTrain=xTrain:cuda()
		yTrain=yTrain:cuda()
	end

======

**Comment by fmassa** [comment]
@chaopengshen if you want to run your code in half precision, you need to run it on the GPU. And depending on the operations, you might not see any speedup actually.
