### ISSUE TITLE
Documentation on THAlloc and THAllocator?

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#300]
Hi,

THAlloc and THAllocator seem to be one of those things that one needs to understand quite clearly, or else get weird errors in ones program at unexpected occasions, or on platforms to which one doesnt have access, so cant debug easily.

Dont suppose... where can I find some documentation that describes:
- high level description of what THAlloc/Allocator are, why we need them, what they do?
- how to use them?
- any caveats and rules one must obey, in order to avoid weird segfaults, unportable behavior etc?

(Anything else, I can just try it and see, read the source code, but allocation seems to be something where it's quite easy to do something really wrong, without any obvious immediate ill-effects)

(Edit: seems like it doesnt handle the ref-counting, right?)

**Comment by timharley** [comment]
There is no documentation. `THAlloc` and friends are internal to TH, which in general is not user facing and *sparsely* documented. The easiest thing will be to read the source code. `THAllocator` doesn't crop up in many places, and it's fairly simple - it just provides 3 function pointers that look like `malloc` `realloc` and `free`. In short, the 2 main reasons why TH abstracts allocation through an allocator are: 
* Attempting to check for failure of `malloc`, and raising a `lua_error` if so (whether this is correct or likely to help is another question).
* Allowing storages to be constructed to point at a memory mapped file, rather than some memory that has been `malloc`ed (https://github.com/torch/torch7/blob/master/lib/TH/THAllocator.h#L22)

Reference counting is done intrusively on THStorage and THTensor objects, not by THAllocator and friends. 
https://github.com/torch/torch7/blob/master/lib/TH/generic/THStorage.h#L28
https://github.com/torch/torch7/blob/master/lib/TH/generic/THTensor.h#L17

One thing that's easy to miss: A THStorage has flags which describe what relationship it has to the memory allocated for the data.
https://github.com/torch/torch7/blob/master/lib/TH/generic/THStorage.h#L22

Hope this helps.

**Comment by hughperkins** [comment]
Thanks.  Good summary.
