### ISSUE TITLE
Tensors and Storages sealed?

### ISSUE THREAD

**Issue by mys007** [torch/torch7#322]
I noticed it is impossible to add object attributes to torch.Tensor/torch.Storage or to derive a subclass:
```
th> T=torch.Tensor()
th> T.myattr=5
[string "T.myattr=5"]:1: the class torch.DoubleTensor cannot be indexed

th> TT,PP=torch.class('torch.ABCTensor','torch.FloatTensor')
th> function TT:__init() PP.__init(self) end
bad argument #1 to '?' (torch.FloatTensor expected, got torch.FloatTensor)
```
In general, this works without problems:
```
th> M=nn.Module()
th> M.myattr=5
th> MM,PP=torch.class('torch.ABCModule','nn.Module')
th> function MM:__init() PP.__init(self) end
```
Is this by design or a bug? Thanks!

**Comment by timharley** [comment]
By design, they are different Lua types:

> print(type(torch.Tensor()))
userdata
> print(type(nn.Linear(1,1)))
table

A torch 'type' describes the metatable of an instance of an object (it's
orthogonal to the Lua type of that object). A torch class is a table that
is a particular torch type. Tensors and Storages are not torch classes, but
are torch types. Inheritance etc is only available for torch classes.
__newindex is not available for Tensors/Storages, but is available for
torch classes.

Hope this helps.

**Comment by mys007** [comment]
Great explanation, it was really difficult to wrap my head around that myself. Thanks.

**Comment by timharley** [comment]
No problem :)
