### ISSUE TITLE
[Roadmap] August 2015 - March 2016

### ISSUE THREAD

**Issue by soumith** [torch/torch7#326]
Hey everyone.

Over the last month or so, Ronan, Clement, Koray and I have been consolidating community and developer feedback, as well as thinking hard on the core design changes needed to keep Torch competitive and effective.

We prepared a first draft of the roadmap, located here:

https://github.com/torch/torch7/blob/master/ROADMAP.md

Everyone is invited to read it, give their opinions, propose changes, and participate in making the roadmap more sensible in your eyes.

We are extremely open to feedback and will incorporate any changes or additions that the majority think that are sensible.

Looking forward to your suggestions.

**Comment by nicholas-leonard** [comment]
Do we add our comments in the wiki? or in this issue?

**Comment by nicholas-leonard** [comment]
My suggestions  :
 * For testing, I think we need recursive tests. For example, recursiveTensorEq and such.
 * Moses would be a great addition. I already have it as a dependency for all my projects. 
 * dp : lots of users, documentation, tutorials and datasets. Used by lots of first-timers (standardized training, works out of the box). I would love to see it included in torch group, or at least endorsed in some manner.
 * iTorch : I would love to use it for more tutorials, but I can't get it to install...
 * General : many of the proposed changes would break compatibility with existing code. For example, making all the packages local instead of global. How are we going to deal with that?

**Comment by soumith** [comment]
Add them to the issue here

**Comment by mrkulk** [comment]
I think better plotting would make a huge difference in the workflow.

**Comment by hughperkins** [comment]
```
    for Lua: 3 spaces
    for C: 2 spaces
```
This means using two different editors for C and Lua files, or changing editor preferences each time one changes between a C and a Lua file.

Strong preference for 2 spaces everywhere.  Consistency.

**Comment by hughperkins** [comment]
```
Packages need to avoid global side effects, and return themselves as simple tables
```

One of the great things about torch, compared to caffe, is the ease with which one can monkey-patch things in.  I'm not sure this should change.

**Comment by hughperkins** [comment]
```
If there is a project that seems good from outside or consortium, how do we endorse/improve/modify that? 
```
- projects are already linked to from the wiki page
- `luarocks` already provides the ability to install community packages easily, and the process to submit ones packages to this is straightforward
- if a project becomes so widely used as to be worth installing always, in every install, then it could be added to the [distro](https://github.com/torch/distro) script
  - such packages will be rare, and really obvious, since maybe 80% of torch users will be using them (probably true eg of cutorch, nn, nngraph, ...)

The way this works currently seems fine to me.

**Comment by hughperkins** [comment]
As a general comment, for all of the backwards-incompatible changes, which includes all three points I have flagged above, I think you might want to think very carefully about what are the concrete benefits, and whether they are worth the plausibly huge disadvantages associated with breaking changes.  I cite in evidence:
- python 3
- gnome 3
- ubuntu unity
- comments on slashdot about [battle of wesnoth](http://games.slashdot.org/comments.pl?sid=7739499&cid=50181755)

**Comment by hughperkins** [comment]
As a general comment, for any backwards-incompatible changes, I think you might want to think very carefully about what are the concrete benefits, and whether they are worth the plausibly huge disadvantages associated with breaking changes.  I cite in evidence:
- python 3
- gnome 3
- ubuntu unity
- comments on slashdot about [battle of wesnoth](http://games.slashdot.org/comments.pl?sid=7739499&cid=50181755)

**Comment by clementfarabet** [comment]
@hughperkins forcing packages to have no side effects shouldn't have a big consequence on productivity / ease of prototyping. This would mostly mean going from:

```lua
require 'nn'
require 'torch'
local net = nn.Sequential()
local t = torch.Tensor()
```

to:

```lua
local nn = require 'nn'
local torch = require 'torch'
local net = nn.Sequential()
local t = torch.Tensor()
```

Having a package produce global side-effects makes things harder to debug, and harder to maintain in general. `th` (trepl) provides a flag "-g" that prints warnings for every global variable created or accessed, and a flag "-gg" to replace warnings by errors. It's very helpful to get warnings, but I'd love to be able to use -gg to produce bullet-proof scripts. Again these flags won't be true by default, but they offer a nice bridge to pushing Torch code in production environments.

**Comment by hughperkins** [comment]
@clementfarabet In the specific, I use eg the following monkey-patch:
```
function FloatTensor.cl(self)
   -- stuff here...
end
```
Then, people can use this simply by doing:
```
require 'cltorch'

local a = torch.Tensor():cl()
```
In the future, they could continue to use cltorch eg by doing:
```
local torch = require 'torch'
local cltorch = require 'cltorch'
cltorch.patchTorch(torch)

local a = torch.Tensor():cl()
```
Is that about right?

**Comment by clementfarabet** [comment]
That's right, but you could also keep doing exactly what you're doing. 

In your package `cltorch`:
```lua
local torch = require ' torch'
function torch.FloatTensor.cl(self)
end
```

Then in the user code:
```lua
local torch = require 'torch'
local cltorch = require 'cltorch'
-- torch.Tensor.cl now exists
```

`require` only loads a package once, so they everywhere you call it, it returns a reference to the same `torch` table. The only difference with before is the the `torch` package is never made global.

**Comment by clementfarabet** [comment]
Also, nothing will forbid you from doing:
```lua
torch = require 'torch'
```
which will make this table global again :-), and be exactly equivalent to what we have now.

**Comment by hughperkins** [comment]
@clementfarabet ok, seems workable.  But, if cltorch can modify torch package, without the user ever explicitly asking it to, then what is the benefit over how it works currently?

**Comment by clementfarabet** [comment]
The only advantage is that packages won't have global side effects, say if
you load a package called "graphics" which itself loads a package called
"utils", and you had a global table called utils, it will protect you from
killing your table. But that's it, then packages will still be modifiable
once required. So it really is a minor change.

**Comment by SalemAmeen** [comment]
I am neither a programmer nor expert in torch but R software has very nice functions for analysing the data like, confusion matrix and its parameters, visualisation ..etc. I sometimes save my data to other format and read it using R software for analysing. So, if there is a way to make interaction between torch7 and other software like R software as people with R software implemented plenty of useful function to deal with data.

**Comment by meharshjoshi93** [comment]
Hello everyone!
Torch is a phenomenal tool! and kudos to the developers :)

However I personally find the iTorch way much more helpful as compared to commandline way.
And it is related to this I would like to raise an issue. 

[SETUP, DEPENDENCIES : BUGS]
From my experience over installing and setting up torch/iTorch environment on up to 10 different machines (a few of them took multiple reinstalls) , I found the process very erratic. For similar configurations, sometimes the setup would work and sometime it wont and throw issues like:

https://github.com/facebook/iTorch/issues/51#issuecomment-127449301

I raised this issue earlier on, however due to the lack of expertise, I couldn't resolve the bug. Surprisingly, the process worked fine on some machines and eventually after 3-4 installs, on the same machine. 

If the community could add this issue to roadmap, it would help speed up on newcomers like me getting onboard

**Comment by deltheil** [comment]
> How do we build a super friendly model zoo? git repo of pre-trained models?

Could [Git Large File Storage](https://git-lfs.github.com/) be an option? (even though it comes with [limited free usage](https://help.github.com/articles/billing-plans-for-git-large-file-storage/))

**Comment by soumith** [comment]
I think that's a good idea. I have it enabled for my username already. And we can see how expensive it gets :)

**Comment by dominikgrewe** [comment]
> Templated C++ in TH Core?

I'd love to see templated tensors in TH. It doesn't have to be anything fancy imo, but using C++ templates instead of macros would be a good step.
@andresy If you have some concrete ideas/code, maybe we can discuss it in a separate issue?

While we're modifying TH, I think we should introduce some kind of state object, similar to THCState in cutorch. With C++, we could make it a class and define all currently global functions as methods of this class. Then we wouldn't need to pass it around everywhere as we do in cutorch. Wdyt?

**Comment by hughperkins** [comment]
C++ templates give really icky compile errors.  They also tend to cause large header-only libraries, that are slow to compile.

The C macros have their own issues, but at least dont generate 10 pages of errors following some tiny typo; and can happily live in the .c/.cpp side.

**Comment by dominikgrewe** [comment]
I don't think templates necessarily lead to bad compiler errors, unless you use heavy template meta-programming, which no-one is suggesting. It will also allow us to cleanly do certain things we can't currently do. Why can't I compare the sizes of tensors of different types, for example?

**Comment by hughperkins** [comment]
Many things are possible using either OOP or templates.  Personally, I think that OOP is cleaner, easier to read.  Templates probably run faster though, since no need for vtables.

**Comment by nicholas-leonard** [comment]
> when does existance of a package stop us from developing the same in core torch?
What do you mean by this?

**Comment by hughperkins** [comment]
For Lua indentation, since 3-spaces seems inevitable, and since I'd prefer to avoid having to switch from gedit to geany/scribes/something, I've created a lua-smudger project, to perform indentation conversion automatically during checkout/commit: https://github.com/hughperkins/lua-smudger

- handles indentation size conversions
- idempotent: can smudge/clean as many times as you like, only the first time will have any effect
- cleans white-space from end of lines
- configurable

**Comment by hughperkins** [comment]
Removed my comment about backwards-incompatible changes.  At the time I wrote it, I didnt realize that Lua standard was 3-spaces.  I had noticed in passing earlier that a lot of Lua files were inconsistently formatted, like 3-spaces instead of 2-spaces, but it never occurred to me that having different indentation according to the file type was the actual standard :-P

Anyway, clnn and cltorch are in 3spaces now, using [lua-smudger](https://github.com/hughperkins/lua-smudger)  It sort of kind of works ok.  You know that the rest of the world uses 4-spaces for everything right?  [pep8](https://www.python.org/dev/peps/pep-0008/) [aviva c# guidlines](https://csharpguidelines.codeplex.com/downloads/get/540283)  Lua apparently uses 2 spaces [LuaStyleGuide](http://lua-users.org/wiki/LuaStyleGuide)

I dont have a problem with Torch using different indentation than the rest of the world, but probably would be good if it was at least consistent with itself :-P

**Comment by lukeyeager** [comment]
Happy to see #262 make the roadmap!

**Comment by szym** [comment]
I noticed the Web UI issue. Happy to contribute there as much as I can.

**Comment by fmassa** [comment]
Splitting `nn` in `THNN` and `nn` is a nice addition. But how should contributions be sent in this case ? Lots of functions can be simply written using basic torch functions in lua, without the need of writing separate C/Cuda versions. Are there going to be redundancy in the code, or is there a way of using the templates (or macros) to avoid this redundancy ?

**Comment by hughperkins** [comment]
Just in case useful, here are things I modified in cltorch, compared to cutorch:

- state device index is now only used at the time of creating a new tensor.  All other tensor operations use the tensor device index instead
- the apply operations are now classes, rather than templated, using OOP rather than templates :-)
- apply, reduce etc are now template free, use OOP instead
  - associated with this, most methods are moved out of the header files, and into the .cpp files
- added int64, int32, which are used in apply and reduce, I think, but not yet globally
- runtime kernel templating, using Lua templates (you can see this as good or bad; my startup times are fast, and I dont have 200MB of files created in ~/.nv on first startup :-P; apply is very clean: https://github.com/hughperkins/cltorch/blob/master/src/lib/THClApply.cpp )
- zero-dimensional tensors, containing a single scalar, used to avoid reduceall operations causing an implicit device->host copy, and associated pipeline stall. bubble bubble!
- apply/map/map2 exist, and run on the GPU, at full speed

**Comment by hughperkins** [comment]
torch as it stands can only be used from Lua.  The hardest, most important parts of Torch are already in C/C++.  It wouldnt take much effort to make Torch 100% C/C++, and thereby be useable from any language.

**Comment by bhack** [comment]
What do you think to better organize github PR and issue with one of this tools at http://liftux.com/posts/using-github-issues-project-management/?
Most of this solutions are free for open source projects (like github account itself). Waffle it is also open source. Not reviewed and opensource also Taiga.io at https://taiga.io/

**Comment by hughperkins** [comment]
(Note: slight update: cltorch is using `uint64_t`/`uint32_t` now, instead of custom `uint64`/`uint32` typedefs, at least in branch, following https://github.com/hughperkins/EasyCL/issues/8)

**Comment by soumith** [comment]
Summarizing the thread so far:
- better plotting / visualization
- binaries / versioning + smoother install
- better tester (in line with moving to Totem)
- git-lfs for modelzoo
- Moses endorsed more in the core
- Move dp to torch org
- C++ templates or C macros

**Comment by hughperkins** [comment]
For templating, note that I actually used jinja2 templates 'in anger' for the Python wrappers poc, and I quite liked the result.  It's true that they're a fairly natural match for python scripts, being python, but I did like:
- fairly clean, no 'magic' (cf C macros)
- normal, standard error messages, no pages-of-weird-errors cos you missed a star or something (cf c++ templates)
- you can see the actual generated code (cf c++ templates), without pages and pages of other embedded headerfiles (cf C macros)

Anyway, I dont realistically reckon that they will be used for C/C++ just yet, without some longer POC, but you can see how they look, and see how much hate/like:
- example for python/cython script: you write [PyTorch.jinja2.pyx](https://github.com/hughperkins/pytorch/blob/master/src/PyTorch.jinja2.pyx), it generates [PyTorch.pyx](https://github.com/hughperkins/pytorch/blob/master/src/PyTorch.pyx)
- example for C++: you write [nnWrapper.jinja2.cpp](https://github.com/hughperkins/pytorch/blob/master/src/nnWrapper.jinja2.cpp), it generates [nnWrapper.cpp](https://github.com/hughperkins/pytorch/blob/master/src/nnWrapper.cpp)

For our usages, we'd probably use Lua as templating language, instead of python/jinja2, but syntax can be very similar, eg this is exactly how the opencl kernel templates work, eg [THClScatter.cl](https://github.com/hughperkins/cltorch/blob/master/src/lib/THClScatter.cl)

**Comment by Kaixhin** [comment]
Looking over the roadmap as a reminder of what's planned for the future, it seems like there are potentially quite a few breaking changes. Are these going to be shelved to preserve backwards compatibility or introduced as some kind of new version of Torch?

I think some variant of [SemVer](http://semver.org/) would be useful, but I realise that's a contentiontious statement for many open source developers.

**Comment by hughperkins** [comment]
Slight nuance on Kaixhin's remark: perhaps it could be worth having a distro of repos, which locks down the git hash of each of the contained repos?  Could be done using git submodules (which work fairly well actually), or could be just a config file.

I think that speaking for myself, I generally dont update torch more than about once a month, so one distro release a month, like 15.10, 15.11, 15.12, etc, could be easy to do, and lock down versioning a bit (I know this isnt semver, but this is at distro level, concept similar to Ubuntu distro).

**Comment by soumith** [comment]
I really wish for static builds, if we go down that route, and i haven't
had time to set up a full static build distro lately. ( it takes a weekend
of mucking around with build stuff). That would be perfect to ship as
binaries.

**Comment by hughperkins** [comment]
Deliverable would be ... the ~/torch directory as a tar file?  A Docker container? rpm/deb?

**Comment by Kaixhin** [comment]
I would image the set of binaries - like `th` and `qtlua` - built for a few platforms, and a package manager - `luarocks` - which would allow the installation of everything else. The nice thing about the local install in `~torch` is that it prevents messing up any other Lua installations and it is easy to remove, but static builds could possibly have global installations.

I'm happy to run bleeding-edge code, so my concern regarding versioning is being able to have some guarantee of running other people's older code, by having versions of packages specified. I don't think it's an issue now, but it could be in the future. Sticking by proper versioning standards is an effort though, so @hughperkins' idea of commit hashes might be a decent solution.

**Comment by hughperkins** [comment]
To lower the barrier a bit on re-indentation, I've created a script which will reindent a lua file, whilst preserving blame :-)  Script is at https://github.com/hughperkins/blameful-indenter  Example of blame after running script:

```
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100  1) local Abs, parent = torc
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100  2) 
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100  3) function Abs:__init()
bc7b818d (Ronan Collobert 2016-01-02 16:19:28 +0800  4)   parent.__init(self)
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100  5) end
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100  6) 
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100  7) function Abs:updateOutpu
66ab53f4 (Andreas Köpf    2016-01-02 16:19:28 +0800  8)   input.THNN.Abs_updateO
66ab53f4 (Andreas Köpf    2016-01-02 16:19:28 +0800  9)     input:cdata(),
66ab53f4 (Andreas Köpf    2016-01-02 16:19:28 +0800 10)     self.output:cdata()
66ab53f4 (Andreas Köpf    2016-01-02 16:19:28 +0800 11)   )
bc7b818d (Ronan Collobert 2016-01-02 16:19:28 +0800 12)   return self.output
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100 13) end
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100 14) 
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100 15) function Abs:updateGradI
66ab53f4 (Andreas Köpf    2016-01-02 16:19:28 +0800 16)   input.THNN.Abs_updateG
66ab53f4 (Andreas Köpf    2016-01-02 16:19:28 +0800 17)     input:cdata(),
66ab53f4 (Andreas Köpf    2016-01-02 16:19:28 +0800 18)     gradOutput:cdata(),
66ab53f4 (Andreas Köpf    2016-01-02 16:19:28 +0800 19)     self.gradInput:cdata
66ab53f4 (Andreas Köpf    2016-01-02 16:19:28 +0800 20)   )
bc7b818d (Ronan Collobert 2016-01-02 16:19:28 +0800 21)   return self.gradInput
^4df3893 (Ronan Collobert 2012-01-25 14:55:20 +0100 22) end
bc7b818d (Ronan Collobert 2016-01-02 16:19:28 +0800 23) 
```
I'd be quite happy, more than happy :-) , to spend a few days going through nn and cunn, changing indentation to 2-spaces, whilst preserving original blame. (Could also do others, eg nngraph, rnn, though I suspect that is not really desired at the moment?)

**Comment by soumith** [comment]
@hughperkins that looks fantastic. That's one of the reasons I didn't want to reindent the whole repo (to loose git blame), but you seem to have solved it.

**Comment by nicholas-leonard** [comment]
So we want to make Lua code 2 space instead of 3?

**Comment by soumith** [comment]
No, we'll leave it as is. But a lot of code is inconsistent in indentation, so probably useful to clean that up.

**Comment by hughperkins** [comment]
Hmmm, that wasnt really my intention in creating blameful-indenter :-P  But fine :-P  It occurred to me that I dont really modify nn or torch7 lua files anyway, just those in clnn, so I will change clnn to 2-spaces and have done with it.  Anyone who points out it is inconsistent, I shall assuage my guilty conscience slightly by pointing out that 3-spaces is itself inconsistent with the C code :-)

(In other news, and entirely off-topic, I noticed yesterday that the C++ files in my jeigen project https://github.com/hughperkins/jeigen/blob/master/src/native/jeigen.cpp are 3-spaced, whilst the java files in the same project are 4-spaced https://github.com/hughperkins/jeigen/blob/master/src/java/jeigen/DenseMatrix.java (or even, mixed tabs and 4-spaces perhaps :-O ) , even though both sets of files are in the same project, and both written by me, at the same time :-D )

**Comment by hughperkins** [comment]
Updated blameful-indenter, to be two-phase:
- first, run `propose_indents.py`, which will create `.proposed`-suffix files, with proposed indentations
  - you can then tweak the indentations by hand
- then run 'commit_indents.py, to commit these changes, preserving blame

Alternatively, you can just copy the old file to have a `.proposed` suffix, hack around the indentation by hand, or using some tool you have, like a text editor, then run `commit_indents.py` to commit the changes, preserving blame.

**Comment by Atcold** [comment]
@hughperkins, can't you simply add
```
autocmd BufNewFile,BufRead *.lua setlocal expandtab tabstop=3 shiftwidth=3 softtabstop=3
autocmd BufNewFile,BufRead *.c   setlocal expandtab tabstop=4 shiftwidth=2 softtabstop=2
```
to your `~/.vimrc` as everybody else?

**Comment by Atcold** [comment]
About formatting, could we impose also spacing after `,`?

Regarding the documentation, could we also impose having 1 line per sentence?
So, if someone changes something, there is no need to rewrap the whole text within 80 characters.
And, when using the *inline* documentation, we avoid having weird splits.

**Comment by soumith** [comment]
@Atcold no about imposing anything. i dont think we are sizeable enough to impose anything, tbh i am still at the state where we are ready to accept any positive contribution.

**Comment by Atcold** [comment]
OK, then I'll keep cleaning code and doc in my spare time :wink:

**Comment by hughperkins** [comment]
> @hughperkins, regarding your first comment above, can't you simply [switch to vim] as anybody else?

I tried a bunch of editors, as a result of the indentation inconsistency, but none of them really worked for me.  My editor of choice is gedit.  You can say that gedit doesnt meet my requirements, since it doesnt handle automated indentation, and you are free to believe that is a perfectly fair assertion.

For now, I've found a solution by realizing I actually don't do many edits to nn and cunn, and will move clnn back to 2 spaces.  All my other lua code repos are 2-spaced.  char-rnn is 4-spaced, which is ok too.  It's at least an integer multiple.  neural-style is sensibly 2-spaced, in line with the torch c-code.

Other solutions include switching to python.  It's actually a big contributing reason behind my creating https://github.com/hughperkins/pytorch .  Surprising, but true :-)

**Comment by hughperkins** [comment]
> Regarding the documentation, could we also impose having 1 line per sentence?

Strangely, I can disagree with one of your assertions, and agree with another.  This seems like quite a reasonable idea in fact... though novel.  It's at least consistent with the way git works, and code works, and will do what it says on the can.  What vim users think of stepping over column 79 I'm not sure :-D

**Comment by Atcold** [comment]
What about adding to every file a descriptive comment on top? Now it's really a mess. One has no idea what a specific file is supposed to do.
I believe some API specifications should be mandatory, if someone expects others to read and contribute to the code.

**Comment by hughperkins** [comment]
> What about adding to every file a descriptive comment on top?

The problem with doc is it tends to get desynchronized from the code, and then its worse than useless: it spreads disinformation.

I've personally learned the entirety of torch7, cutorch, cunn, based on the existing code, and a few questions into https://groups.google.com/forum/#!forum/torch7 occasionally, which Soumith and others are incredibly proactive about replying to.  And I found it fairly straightforward.  On a scale of nightmare-to-read-spaghetti as 0 to easy-to-read being 10, I'm going to put it around an 8 or 9, in my opinion.  The fact that my main complaints are about indentation rather than refactorization seems to lend support to this assertion...

**Comment by Atcold** [comment]
@hughperkins, I think it's quite subjective.
If you are an experienced programmer, then you can *understand* code by "reading" it.
For who is less able, reading some English would be definitely essential to start delving into the source code.
At least, speaking at personal title, I have no clue about how the thing is actually working. I can program in C and Lua, but there is no big picture explanation whatsoever. So, I have no clue where to start. The project is too big for an unexperienced programmer to start making sense without some guidance.

**Comment by hughperkins** [comment]
> If you are an experienced programmer, then you can understand code by "reading" it.
For who is less able, reading some English would be definitely essential to start delving into the source code.

I think you are overestimating ability to read code to be honest ;-)  What I normallly do is start to make notes, along the lines of https://github.com/hughperkins/cltorch/blob/d8ba3f7e5112c9e1ccc1a56a292f8f0eac4ce293/doc/torch/torch.md or https://github.com/hughperkins/rnn-notes  But these notes are pretty personal, and it's not normally the contents of the notes that are themselves directly useful, so much as the process of taking them, making them.

That said the said-cited notes at https://github.com/hughperkins/cltorch/blob/d8ba3f7e5112c9e1ccc1a56a292f8f0eac4ce293/doc/torch/torch.md are what I was using/making, and do contain a fair amount of description.  I could rename them to Architecture.md, or ImplementationNotes.md, or similar, and put them somewhere, if that would be useful?

**Comment by Atcold** [comment]
@hughperkins, I believe they would be very useful (although I'm not sure where they could find space). I may overestimate the ability to read code maybe because it is something I've never been taught (and which I am learning now by going over my first Algorithms class). And well, yes, I understand that you can learn it by your own, but I find English way more intuitive than some abstract programming language.

**Comment by hughperkins** [comment]
@Atcold  Ok.  Well... I think they're a bit too rough and ready, and already out of date, and unmaintainable, to add to core torch, but maybe I'll create a repo like 'torch-notes', and put them in that.

**Comment by hughperkins** [comment]
https://github.com/hughperkins/torch-modder-notes

**Comment by viper7882** [comment]
Hi @soumith ,

I'm aware it is 2017 year now.

Quick sharing: @hughperkins has created [Coriander](https://github.com/hughperkins/coriander-dnn) that could run NVIDIA® CUDA™ code on OpenCL 1.2 devices. You might want to take a look if that suits your need to connect Torch with OpenCL 1.2 devices. I'll let @hughperkins to comment more on his work if you would like to learn more.

**Comment by wickedfoo** [comment]
@viper7882 That's only a (partial) implementation of the cuDNN API, not of CUDA itself.

**Comment by hughperkins** [comment]
Hi @wickedfoo So... [Coriander-dnn](https://github.com/hughperkins/coriander-dnn) is indeed a partial implementation of the NVIDIA® cuDNN API, not of NVIDIA® CUDA™ itself.

However, [Coriander](https://github.com/hughperkins/coriander) is a compiler and runtime to build NVIDIA® CUDA™ code for OpenCL™ 1.2 devices ;-)

**Comment by hughperkins** [comment]
Hmmmm, a lot happened since this thread was created, some good, some bad, a mixture ... :
- Deepmind quit Torch (bad... :-( )
- Torch moved to Python (good :-) )
- THNN meant I quit cltorch (bad :-( )
- so I worked on Coriander instead (good?)
- but I started by using it first on tf (probably bad, but kind of fun :-) )
