### ISSUE TITLE
NaN output when using SpatialConvolutionMap

### ISSUE THREAD

**Issue by OsamaSultan** [torch/torch7#343]
Hello,
On my computer, the code in the gist below will produce output that contains NaNs in the end. However, there are three cases where it will be normal without NaNs:

1 - Commenting out the custom SpatialConvolutionMap (line 42), and adding SpatialConvolutionMM instead (line 41). (Will work in all cases)
2 - Commenting out stage 3 of the network (lines 54,55)
3 - Uncommenting --require 'image' in line 2 (??!!)

This is the part of the problem that I could produce a minimal example of. In my code however I had to change the architecture of the model (case 1 from above) in order to avoid the NaNs. I find case 3 very strange though. Any solutions/explanations?

{% gist 3d9461bd9e3cebca1ffa %}

https://gist.github.com/OsamaSultan/3d9461bd9e3cebca1ffa

**Comment by fmassa** [comment]
@OsamaSultan I tried running your code, but I get a segmentation fault.
The problem you have is due to your `ConMatrix1`. Actually, `SpatialConvolutionMap` supposes that the connectivity table is contiguous (https://github.com/torch/nn/blob/master/generic/SpatialConvolutionMap.c#L24), and yours is not (because of the transpose in https://gist.github.com/OsamaSultan/3d9461bd9e3cebca1ffa#file-nantest-lua-L28). Just add a `:contiguous()` after the transpose and it works.
Also, problems with `nn` should be sent to https://github.com/torch/nn
