### ISSUE TITLE
torch.multinomial can't be used without allocating memory

### ISSUE THREAD

**Issue by kosklain** [torch/torch7#359]
The docs mention that the function can be used as  `torch.multinomial([res,], p, n, [,replacement])` but calling `torch(res, p, n)` does not seem to work, it simply fails mentioning that torch.LongTensor does not implement torch.multinomial.

**Comment by fmassa** [comment]
This is a similar problem than the one mentioned in https://github.com/torch/torch7/issues/231 , because the output of `multinomial` is supposed to be a `LongTensor`, and when you call it with `torch.multinomial` it looks for the type of it's first argument (which is a `LongTensor`), but `multinomial` expects `p` to be `FloatTensor` or `DoubleTensor`.

But there is actually a workaround for this, which is to call it as `p.multinomial(res,p,n,[replacement])`. This way, you explicitly specify that you want to call it for the type of tensor `p`.

**Comment by kosklain** [comment]
That indeed works as a workaround, thanks!

**Comment by soumith** [comment]
Added doc for the issue, via commit: https://github.com/torch/torch7/commit/656a4a20a2e8f048657cff3bd51b355a3c99b4d6
