### ISSUE TITLE
Not building on Broadwell cpus

### ISSUE THREAD

**Issue by geevi** [torch/torch7#431]
Due to a bug in the openblas build for broadwell cpus, the automated script (install-dep) doesnt work.

There is a temporary fix, by editing the automated script (install-deps),  adding TARGET=HASWELL in the make instruction for Openblas.

**Comment by soumith** [comment]
This is probably because we're on the OpenBLAS master branch, rather than the develop branch. Fixed it via https://github.com/torch/ezinstall/commit/da8d760031cca0fbaa9ccfd8ece7a8c396c9fa1d

Next time, please report install issue on the google groups, or directly on: https://github.com/torch/distro/issues
