### ISSUE TITLE
Tensor table literal syntax

### ISSUE THREAD

**Issue by binarymax** [torch/torch7#501]
Hi!  This is a question and not an issue.

I am trying to better understand this syntax in Lua while accessing Tensors:

```lua
local ten = torch.Tensor{{1,2,3},{4,5,6},{7,8,9}}

for i=1,(#ten)[2] do
    print(ten[i][{{2}}])
end
```

Specifically the line

```lua
    print(ten[i][{{2}}])
```

When I run the code, it prints

```
 2
[torch.DoubleTensor of size 1]

 5
[torch.DoubleTensor of size 1]

 8
[torch.DoubleTensor of size 1]
```

I am familiar with table literals and their basic syntax, but what is the purpose of wrapping the '2' in double curly-braces, and how does it work in the engine and tensor library?

**Comment by fmassa** [comment]
@binarymax Have a look at [this part of the documentation](https://github.com/torch/torch7/blob/master/doc/tensor.md#tensor--dim1dim2--or--dim1sdim1e-dim2sdim2e-).

* When you have single curly-braces, you are creating a [selection of the tensor](https://github.com/torch/torch7/blob/master/generic/Tensor.c#L935-L947). So `ten[{1}]` is [equivalent](https://github.com/torch/torch7/blob/master/generic/Tensor.c#L882-L902) to `ten[1]`, which is in turn equivalent to `ten:select(1,1)`. If you have several indices like `ten[{1,2}]`, this is also equivalent to the slower `ten[1][2]` (because the latter returns 2 times a tensor, whereas the former only returns it once). If you select on a 1D tensor, your output is a number.
* When you have double curly-braces, it returns a [`narrow` of the tensor](https://github.com/torch/torch7/blob/master/generic/Tensor.c#L948-L972), and a `narrow`ed tensor is always a tensor (even if it only has one element). With double curly-braces, you can specify a range in which the tensor will be narrowed, which is not possible with single curly-braces. For example, you can do `ten[{{1,2},1}]`, which will be a 1D tensor of dimension `2`, and if your do `ten[{{1,2},{2}}]` it will return a 2D tensor of size `2x1`.

For more information, have a look at [`select`](https://github.com/torch/torch7/blob/master/doc/tensor.md#tensor-selectdim-index) and [`narrow`](https://github.com/torch/torch7/blob/master/doc/tensor.md#self-narrowdim-index-size).
One last note, the doc for `select` is not precisely correct, as it's possible to do a select on a 1D tensor, and the output is a number.

**Comment by binarymax** [comment]
Thank you @fmassa, this is very clear.
