### ISSUE TITLE
Make nn C functions available as torch functions.

### ISSUE THREAD

**Issue by shawnjhenry** [torch/torch7#513]
It would be really useful to have some (all?) of the nn module C functions available as regular torch functions for building compound modules.  For example, torch.relu or torch.softmax could be really useful for certain kinds of nets.  (E.g. recurrent nets where we can't use an nn module because it reuses data from the forward prop in back prop.)  What do folks think about this?

**Comment by fmassa** [comment]
There is a work in progress ([THNN](https://github.com/torch/nn/tree/master/lib/THNN)) which is factoring out all C functions from `nn` so that they are [completely functional and independent of internal states](https://github.com/torch/nn/issues/506). With that, you could call any C function from nn by doing something like
```lua
input.THNN.Abs_updateOutput(input:cdata(),self.output:cdata())
```

BTW, both sigmoid and relu functions you mentioned are already in torch (`sigmoid` was introduced this week, and relu is simply `torch.cmax(x,0)`).

**Comment by shawnjhenry** [comment]
Great!  I knew about sigmoid.  ReLU was really what I was after - good to know it's already implemented.  Thanks!
