### ISSUE TITLE
Memory leaks after a few epochs

### ISSUE THREAD

**Issue by arnabgho** [torch/torch7#683]
I had defined a Neural Network but after a few epochs it leads to memory leaks and garbage values corrupting the output.

I reached the conclusion because when I reduce the number of network parameters it actually ran for greater number of epochs.

I have tried collectgarbage() and using local variables , but still the issue persists

**Comment by soumith** [comment]
Because there is no clear bug report, or reproducing mechanism, I'm closing this as an issue. Let's continue the discussion on our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
