### ISSUE TITLE
The metatable is dropped from torch.class if returned via custom __index__

### ISSUE THREAD

**Issue by gforge** [torch/torch7#693]
There seems to be inconsistent behavior when overloading the `__index__` function in `torch.class`. The metatable is dropped if the `__index__` returns if an object is returned from the method. As I'm trying to implement the `__index__` on a [Dataframe](https://github.com/AlexMili/torch-dataframe/issues/18) this is problematic. Below is a simple example:

```lua
require 'torch'

local a = torch.class('A torch class')

function a:__index__(index)
  if (type(index) == "number") then
    local tmp = self:_create_a_new()
    print(torch.type(tmp))
    return tmp
  end
  return rawget(self, index)
end

function a:_create_a_new()
  return a.new()
end

test = a.new()
print(type(getmetatable(test)))
print(torch.type(test:_create_a_new()))

print("\n-------\nSubset")
local sub = test[1]
print(type(getmetatable(sub)))
print(torch.type(sub))
print("-------")
```

outputs:

```
table    
A torch class    

-------
Subset    
A torch class    
nil    
table    
-------    
```

Note that this behavior is the same if we try to return a different class:

```lua
require 'torch'

local a = torch.class('A torch class')
local b = torch.class('Another class')

function a:__index__(index)
  if (type(index) == "number") then
    local tmp = b.new()
    print(torch.type(tmp))
    return tmp
  end
  return false -- Also tried this as suggested by https://github.com/torch/torch7/tree/master/lib/luaT#operator-overloading
end

function a:_create_a_new()
  return a.new()
end

test = a.new()
print(type(getmetatable(test)))
print(torch.type(test:_create_a_new()))

print("\n-------\nSubset")
local sub = test[1]
print(type(getmetatable(sub)))
print(torch.type(sub))
print("-------")
```

The output for this is:

```
table	
A torch class	

-------
Subset	
Another class	
nil	
table	
-------	
```

**Comment by soumith** [comment]
I've fixed your example slightly. 

```lua
require 'torch'

do
   local b = torch.class('B')
end

do
   local a = torch.class('A')

   function a:__index__(index)
      if (type(index) == "number") then
         local tmp = B.new()
         print(torch.type(tmp))
         return tmp
      end
      return false -- Also tried this as suggested by https://github.com/torch/torch7/tree/master/lib/luaT#operator-overloading
   end

   function a:_create_a_new()
      return self.new()
   end
end

test = A.new()
print(type(getmetatable(test)))
print(torch.type(test:_create_a_new()))

print("\n-------\nSubset")
local sub = test[1]
print(type(getmetatable(sub)))
print(torch.type(sub))
print("-------")
```

**Comment by soumith** [comment]
But the issues still exists. I'll have to dig deep into what's going on.

**Comment by albanD** [comment]
Hi,

 The problem is that `__index__` should always return a boolean value saying whether or not it worked.
You did it in the `false` case but not in the correct case. The following sample works as expected:
```lua
require 'torch'

do
   local b = torch.class('B')
end

do
   local a = torch.class('A')

   function a:__index__(index)
      if (type(index) == "number") then
         local tmp = B.new()
         print(torch.type(tmp))
         return tmp, true
      end
      return false -- Also tried this as suggested by https://github.com/torch/torch7/tree/master/lib/luaT#operator-overloading
   end

   function a:_create_a_new()
      return self.new()
   end
end

test = A.new()
print(type(getmetatable(test)))
print(torch.type(test:_create_a_new()))

print("\n-------\nSubset")
local sub = test[1]
print(type(getmetatable(sub)))
print(torch.type(sub))
print("-------")
```

You can see this in the [`__index__` implementation for Tensors](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/generic/Tensor.c#L878-L1001): correct cases are always returning the value AND a `true` boolean flag [here](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/generic/Tensor.c#L902), [here](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/generic/Tensor.c#L920), [here](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/generic/Tensor.c#L985) and [here](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/generic/Tensor.c#L993). The failure case is [here](https://github.com/torch/torch7/blob/eb8d7f2752f2b714135b862d148600c60329ac26/generic/Tensor.c#L998). There is a note in the luaT code [here](https://github.com/torch/torch7/blob/bed42e94114daa006a762af28f16d12a79ffea86/lib/luaT/luaT.c#L1116) that warns you that you should always return both values.

**Comment by gforge** [comment]
Thanks, somehow I failed to see the "value" in [the docs](https://github.com/torch/torch7/tree/master/lib/luaT#operator-overloading):

> must either return a value and `true` or return `false` only.

As the `true` and `false` are formatted as code I guess my eye didn't notice the vital "value". A possible improvement could be:

* `__index__` must either return (1) two values: a value and `true` or (2) a single value:  `false`. In the first case, it means `__index__` was able to handle the given argument (for e.g., the type was correct). The second case means it was not able to do anything, so `__index` in the root metatable can then try to see if the metaclass contains the required value.

To me this was unexpected behavior although I now can appreciate that this solution since it elegantly allows `__index__` to return `false` as an actual value. 

Anyway, thanks for the help and my apologies for this faulty report.
