### ISSUE TITLE
torch.range can return wrong values

### ISSUE THREAD

**Issue by ViliusT** [torch/torch7#717]
See below:

```
local value = 843
local range_value = torch.range(0.01, value*0.01, 0.01) 
print (value, range_value:size(1))

local value = 844
local range_value = torch.range(0.01, value*0.01, 0.01) 
print (value, range_value:size(1))

local value = 845
local range_value = torch.range(0.01, value*0.01, 0.01) 
print (value, range_value:size(1))

local value = 846
local range_value = torch.range(0.01, value*0.01, 0.01) 
print (value, range_value:size(1))


```

Resulting sizes from the command: 
```
843	843	
844	843	
845	844	
846	846	

```
They should all be the same, however, value of 844 and 845 return wrong size for the range tensor.

**Comment by andreaskoepf** [comment]
@ViliusT Responsible for the observed behaviour is [THTensorMath.c#L1405](https://github.com/torch/torch7/blob/58b9acd72bc39b3ea3b0426fc52fd28ffb0d7f97/lib/TH/generic/THTensorMath.c#L1405).

The cast to long does floor rounding. You can also see this in pure lua:
```
> math.floor(0.01 * 845 / 0.01)
844
> math.floor(0.01 * 845 / 0.01 + 0.5)
845
```
In general this is not a bug but just the way floating point works. The problem is that the expression `(0.01 * 845 / 0.01) < 845` evaluates to true. This is not only the case in torch/lua but also in other languages, e.g. if you check with python you will get

```
>>> 0.01 * 845 / 0.01
844.9999999999999
```

A different rounding mode than floor (as demonstrated by the +0.5) could be used but that is a design decission.

In general I recommend reading: [What Every Computer Scientist Should Know About Floating-Point Arithmetic](What Every Computer Scientist Should Know About Floating-Point Arithmetic).

**Comment by ViliusT** [comment]
@andreaskoepf Thank you - I figured out that this must be some sort of a rounding error; The article provided was very useful!
