### ISSUE TITLE
Compilation on Raspberry Pi B+ armv6l

### ISSUE THREAD

**Issue by eaa3** [torch/torch7#807]
Hi there,

I am trying to compile torch on a Raspberry Pi B+ with armv6l (on raspian) and it fails reporting the following error:

```
[  3%] Built target luaT
[  6%] Building C object lib/TH/CMakeFiles/TH.dir/THVector.c.o
In file included from /home/pi/torch/pkg/torch/lib/TH/THVector.c:2:0:
/home/pi/torch/pkg/torch/lib/TH/generic/THVectorDispatch.c: In function ‘THByteVector_vectorDispatchInit’:
/home/pi/torch/pkg/torch/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in ‘asm’
   asm volatile ( "cpuid\n\t"
   ^
/home/pi/torch/pkg/torch/lib/TH/generic/simd/simd.h:64:3: error: impossible constraint in ‘asm’
   asm volatile ( "cpuid\n\t"
   ^
lib/TH/CMakeFiles/TH.dir/build.make:330: recipe for target 'lib/TH/CMakeFiles/TH.dir/THVector.c.o' failed
make[2]: *** [lib/TH/CMakeFiles/TH.dir/THVector.c.o] Error 1
CMakeFiles/Makefile2:129: recipe for target 'lib/TH/CMakeFiles/TH.dir/all' failed
make[1]: *** [lib/TH/CMakeFiles/TH.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
```

More details about the raspberry below:

```
pi@raspberrypi:~/torch $ uname -a
Linux raspberrypi 4.4.11+ #888 Mon May 23 20:02:58 BST 2016 armv6l GNU/Linux
```

I have seen a similar issue on https://github.com/torch/torch7/issues/794
Is there a related fix?

**Comment by jkerfs** [comment]
I received the same error when compiling on a Jetson TX1 (arm64).

My solution was to add the following at the top of `/home/[USERNAME]/torch/pkg/torch/lib/TH/generic/simd/simd.h`:

```
#if !defined(__NEON__) && defined(__ARM_NEON)
#define __NEON__ 1
#endif
```

The issue is that the `cpuid` function is only applicable for x86 architectures.  If the Raspberry Pi does not have support for NEON (and does not set the __ARM_NEON flag) then you are better off just commenting out the offending `cpuid` function.
